# DDOS DETECTION SYSTEM

- Dataset [https://www.kaggle.com/jacobvs/ddos-attack-network-logs?select=final-dataset.arff]

- 


## Importing Required Modules

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix

## Loading the dataset

In [2]:
data=pd.read_csv("final-dataset.csv")
data.head()

C:\Users\sravani\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (18) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


SRC_ADD  DES_ADD  PKT_ID  FROM_NODE  TO_NODE PKT_TYPE  PKT_SIZE    FLAGS  \
0     3.00    24.30  389693         21       23      tcp      1540  -------   
1    15.00    24.15  201196         23       24      tcp      1540  -------   
2    24.15    15.00   61905         23       22      ack        55  -------   
3    24.90     9.00  443135         23       21      ack        55  -------   
4    24.80     8.00  157335         23       21      ack        55  -------   

   FID  SEQ_NUMBER  ...  PKT_RATE  BYTE_RATE PKT_AVG_SIZE UTILIZATION  \
0    4       11339  ...   328.241   505490.0       1540.0    0.236321   
1   16        6274  ...   328.206   505437.0       1540.0    0.236337   
2   16        1930  ...   328.206    18051.3         55.0    0.008441   
3   10       12670  ...   328.064    18043.5         55.0    0.008437   
4    9        4901  ...   328.114    18046.2         55.0    0.008438   

   PKT_DELAY  PKT_SEND_TIME  PKT_RESEVED_TIME  FIRST_PKT_SENT  \
0        0.0      35.519662         35.550032        1.000000   
1        0.0      20.156478         20.186848        1.000000   
2        0.0       7.039952          7.069962        1.030045   
3        0.0      39.617967         39.647976        1.030058   
4        0.0      16.029803         16.059813        1.030054   

  LAST_PKT_RESEVED  PKT_CLASS  
0        50.021920     Normal  
1        50.030211     Normal  
2        50.060221  UDP-Flood  
3        50.060098     Normal  
4        50.061864     Normal  

[5 rows x 28 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977025 entries, 0 to 977024
Data columns (total 28 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   SRC_ADD           977025 non-null  float64
 1   DES_ADD           977025 non-null  float64
 2   PKT_ID            977025 non-null  int64  
 3   FROM_NODE         977025 non-null  int64  
 4   TO_NODE           977025 non-null  int64  
 5   PKT_TYPE          977025 non-null  object 
 6   PKT_SIZE          977025 non-null  int64  
 7   FLAGS             977025 non-null  object 
 8   FID               977025 non-null  int64  
 9   SEQ_NUMBER        977025 non-null  int64  
 10  NUMBER_OF_PKT     977025 non-null  int64  
 11  NUMBER_OF_BYTE    977025 non-null  int64  
 12  NODE_NAME_FROM    977025 non-null  object 
 13  NODE_NAME_TO      977024 non-null  object 
 14  PKT_IN            977023 non-null  float64
 15  PKT_OUT           977023 non-null  float64
 16  PKT_R             97

In [4]:
data.describe()

SRC_ADD        DES_ADD         PKT_ID      FROM_NODE  \
count  977025.000000  977025.000000  977025.000000  977025.000000   
mean       14.460194      18.243119  290238.604907      19.589946   
std         8.769697       8.542978  195616.043087       6.281343   
min         0.000000       0.000000       0.000000       0.000000   
25%         7.000000      11.000000  101227.000000      21.000000   
50%        14.000000      24.130000  281220.000000      22.000000   
75%        24.130000      24.370000  461656.000000      23.000000   
max        26.000000      26.000000  641599.000000      26.000000   

             TO_NODE       PKT_SIZE            FID    SEQ_NUMBER  \
count  977025.000000  977025.000000  977025.000000  9.770250e+05   
mean       20.829160    1054.529304      13.933393  1.853144e+04   
std         5.282073    3321.060303      10.974616  1.375221e+05   
min         0.000000      55.000000       0.000000 -1.000000e+00   
25%        21.000000      55.000000       5.000000  2.354000e+03   
50%        23.000000    1000.000000      11.000000  5.552000e+03   
75%        23.000000    1540.000000      21.000000  1.074900e+04   
max        26.000000   65535.000000      40.000000  3.015537e+06   

       NUMBER_OF_PKT  NUMBER_OF_BYTE  ...          PKT_R  PKT_DELAY_NODE  \
count  977025.000000    9.770250e+05  ...  977023.000000   977023.000000   
mean    13472.640645    1.139637e+07  ...      31.354636        0.001084   
std      4264.981917    1.054476e+07  ...      17.954607        0.051374   
min         9.000000    6.050000e+02  ...       0.015243       -0.039216   
25%      9108.000000    8.850600e+05  ...      16.672206        0.000000   
50%     16091.000000    6.250000e+06  ...      30.936930        0.000000   
75%     16092.000000    2.478010e+07  ...      43.808412        0.000000   
max     16103.000000    2.479860e+07  ...      75.999821       50.025737   

          BYTE_RATE   PKT_AVG_SIZE    UTILIZATION      PKT_DELAY  \
count  9.770220e+05  977022.000000  977022.000000  977022.000000   
mean   3.319479e+05    1054.528603       0.108684       0.005852   
std    3.989866e+05    3321.072866       0.100563       0.019870   
min    5.378760e+01      55.000000       0.000006      -0.114464   
25%    1.805740e+04      55.000000       0.008441       0.000000   
50%    1.249430e+05    1000.000000       0.059605       0.000000   
75%    5.055260e+05    1540.000000       0.236321       0.000844   
max    1.677420e+06   65535.200000       0.236498       0.153680   

       PKT_SEND_TIME  PKT_RESEVED_TIME  FIRST_PKT_SENT  LAST_PKT_RESEVED  
count  977022.000000     977022.000000   977022.000000     977022.000000  
mean       31.332666         31.365501        5.171337         50.683292  
std        17.953541         17.955156        9.081897         16.599191  
min         0.000000          0.030015        0.000000          1.756152  
25%        16.651158         16.682931        1.000000         50.021920  
50%        30.917858         30.949170        1.030016         50.040685  
75%        43.786495         43.818602        1.030051         50.060098  
max        75.983741         75.999821       25.000000         75.999821  

[8 rows x 22 columns]

In [5]:
data.shape

(977025, 28)

## Data Preprocessing

In [6]:
data.columns

Index(['SRC_ADD', 'DES_ADD', 'PKT_ID', 'FROM_NODE', 'TO_NODE', 'PKT_TYPE',
       'PKT_SIZE', 'FLAGS', 'FID', 'SEQ_NUMBER', 'NUMBER_OF_PKT',
       'NUMBER_OF_BYTE', 'NODE_NAME_FROM', 'NODE_NAME_TO', 'PKT_IN', 'PKT_OUT',
       'PKT_R', 'PKT_DELAY_NODE', 'PKT_RATE', 'BYTE_RATE', 'PKT_AVG_SIZE',
       'UTILIZATION', 'PKT_DELAY', 'PKT_SEND_TIME', 'PKT_RESEVED_TIME',
       'FIRST_PKT_SENT', 'LAST_PKT_RESEVED', 'PKT_CLASS'],
      dtype='object')

In [7]:
data_missing_values = data.isnull().sum()
data_missing_values

SRC_ADD             0
DES_ADD             0
PKT_ID              0
FROM_NODE           0
TO_NODE             0
PKT_TYPE            0
PKT_SIZE            0
FLAGS               0
FID                 0
SEQ_NUMBER          0
NUMBER_OF_PKT       0
NUMBER_OF_BYTE      0
NODE_NAME_FROM      0
NODE_NAME_TO        1
PKT_IN              2
PKT_OUT             2
PKT_R               2
PKT_DELAY_NODE      2
PKT_RATE            2
BYTE_RATE           3
PKT_AVG_SIZE        3
UTILIZATION         3
PKT_DELAY           3
PKT_SEND_TIME       3
PKT_RESEVED_TIME    3
FIRST_PKT_SENT      3
LAST_PKT_RESEVED    3
PKT_CLASS           3
dtype: int64

In [61]:
ndata=data.dropna()
ndata.isnull().sum()

SRC_ADD             0
DES_ADD             0
PKT_ID              0
FROM_NODE           0
TO_NODE             0
PKT_TYPE            0
PKT_SIZE            0
FLAGS               0
FID                 0
SEQ_NUMBER          0
NUMBER_OF_PKT       0
NUMBER_OF_BYTE      0
NODE_NAME_FROM      0
NODE_NAME_TO        0
PKT_IN              0
PKT_OUT             0
PKT_R               0
PKT_DELAY_NODE      0
PKT_RATE            0
BYTE_RATE           0
PKT_AVG_SIZE        0
UTILIZATION         0
PKT_DELAY           0
PKT_SEND_TIME       0
PKT_RESEVED_TIME    0
FIRST_PKT_SENT      0
LAST_PKT_RESEVED    0
PKT_CLASS           0
dtype: int64

In [114]:
data_values = data.isna().sum()
data_values

SRC_ADD             0
DES_ADD             0
PKT_ID              0
FROM_NODE           0
TO_NODE             0
PKT_TYPE            0
PKT_SIZE            0
FLAGS               0
FID                 0
SEQ_NUMBER          0
NUMBER_OF_PKT       0
NUMBER_OF_BYTE      0
NODE_NAME_FROM      0
NODE_NAME_TO        1
PKT_IN              2
PKT_OUT             2
PKT_R               2
PKT_DELAY_NODE      2
PKT_RATE            2
BYTE_RATE           3
PKT_AVG_SIZE        3
UTILIZATION         3
PKT_DELAY           3
PKT_SEND_TIME       3
PKT_RESEVED_TIME    3
FIRST_PKT_SENT      3
LAST_PKT_RESEVED    3
PKT_CLASS           3
dtype: int64

In [115]:
nandata=data.dropna()
nandata.isna().sum()

SRC_ADD             0
DES_ADD             0
PKT_ID              0
FROM_NODE           0
TO_NODE             0
PKT_TYPE            0
PKT_SIZE            0
FLAGS               0
FID                 0
SEQ_NUMBER          0
NUMBER_OF_PKT       0
NUMBER_OF_BYTE      0
NODE_NAME_FROM      0
NODE_NAME_TO        0
PKT_IN              0
PKT_OUT             0
PKT_R               0
PKT_DELAY_NODE      0
PKT_RATE            0
BYTE_RATE           0
PKT_AVG_SIZE        0
UTILIZATION         0
PKT_DELAY           0
PKT_SEND_TIME       0
PKT_RESEVED_TIME    0
FIRST_PKT_SENT      0
LAST_PKT_RESEVED    0
PKT_CLASS           0
dtype: int64

## Visualization

ms.matrix(data)

## Dataframe Creation

In [116]:
fdata=pd.DataFrame(data,columns=['SRC_ADD','DES_ADD','PKT_ID','FROM_NODE','TO_NODE','PKT_TYPE','PKT_SIZE','FLAGS','FID','PKT_RATE','BYTE_RATE','PKT_AVG_SIZE','UTILIZATION','PKT_DELAY','PKT_SEND_TIME','PKT_RESEVED_TIME','FIRST_PKT_SENT','LAST_PKT_RESEVED','PKT_CLASS'])
fdata=fdata.sample(n=3000)
fdata

SRC_ADD  DES_ADD  PKT_ID  FROM_NODE  TO_NODE PKT_TYPE  PKT_SIZE  \
758701    12.20    24.54   21921         23       24      cbr      1500   
5282      12.10    24.32  592525         22       23      cbr      1000   
269110     5.00    24.50  156294          5       21      tcp      1540   
652271    19.10    24.39  585756         23       24      cbr      1000   
439803    24.10    10.00  364307         24       23      ack        55   
...         ...      ...     ...        ...      ...      ...       ...   
441129     6.10    24.26  586343          6       21      cbr      1000   
53863      6.00    24.60  539099         21       23      tcp      1540   
185612     2.00    24.20  195349          2       21      tcp      1540   
202773    24.13    13.00   68748         24       23      ack        55   
422081     4.00    24.40   72956          4       21      tcp      1540   

          FLAGS  FID PKT_RATE  BYTE_RATE  PKT_AVG_SIZE  UTILIZATION  \
758701  -------   33  962.685  1444030.0        1500.0     0.123811   
5282    -------   33  124.943   124943.0        1000.0     0.059605   
269110  -------    6  328.205   505434.0        1540.0     0.236321   
652271  -------   40  124.941   124941.0        1000.0     0.059605   
439803  -------   11  328.562    18070.9          55.0     0.008446   
...         ...  ...      ...        ...           ...          ...   
441129  -------   27  124.942   124942.0        1000.0     0.059605   
53863   -------    7  328.193   505416.0        1540.0     0.236321   
185612  -------    3  328.264   505526.0        1540.0     0.236321   
202773  -------   14   328.46    18065.3          55.0     0.008446   
422081  -------    5  328.218   505455.0        1540.0     0.236321   

        PKT_DELAY  PKT_SEND_TIME  PKT_RESEVED_TIME  FIRST_PKT_SENT  \
758701   0.033071      21.420143         21.453214        1.000000   
5282     0.000400      55.512000         55.542640       25.000000   
269110   0.000000      15.929028         15.959397        1.000000   
652271   0.001520      52.816000         52.847760       25.000000   
439803   0.000000      33.572864         33.602874        1.030013   
...           ...            ...               ...             ...   
441129   0.000960      53.056000         53.087200       25.000000   
53863    0.000124      46.979472         47.009965        1.000000   
185612   0.000000      19.605427         19.635797        1.000000   
202773   0.000000       7.681331          7.711341        1.030032   
422081   0.000000       8.079406          8.109776        1.000000   

        LAST_PKT_RESEVED  PKT_CLASS  
758701          9.990480  UDP-Flood  
5282           75.022640     Normal  
269110         50.027339     Normal  
652271         75.023760     Normal  
439803         50.040562     Normal  
...                  ...        ...  
441129         75.023200     Normal  
53863          50.029102     Normal  
185612         50.018467     Normal  
202773         50.055747     Normal  
422081         50.025368     Normal  

[3000 rows x 19 columns]

## Label Encoding

In [117]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [118]:
fdata['PKT_TYPE']

758701    cbr
5282      cbr
269110    tcp
652271    cbr
439803    ack
         ... 
441129    cbr
53863     tcp
185612    tcp
202773    ack
422081    tcp
Name: PKT_TYPE, Length: 3000, dtype: object

In [119]:
fdata.PKT_TYPE.unique()

array(['cbr', 'tcp', 'ack', 'ping'], dtype=object)

In [120]:
fdata['PKT_TYPE']= label_encoder.fit_transform(fdata['PKT_TYPE'])
fdata['PKT_TYPE'].unique()

array([1, 3, 0, 2])

In [121]:
fdata['PKT_TYPE']

758701    1
5282      1
269110    3
652271    1
439803    0
         ..
441129    1
53863     3
185612    3
202773    0
422081    3
Name: PKT_TYPE, Length: 3000, dtype: int32

In [122]:
fdata['PKT_TYPE']=fdata['PKT_TYPE'].astype(float)
fdata['PKT_TYPE']

758701    1.0
5282      1.0
269110    3.0
652271    1.0
439803    0.0
         ... 
441129    1.0
53863     3.0
185612    3.0
202773    0.0
422081    3.0
Name: PKT_TYPE, Length: 3000, dtype: float64

In [123]:
fdata['FLAGS']


758701    -------
5282      -------
269110    -------
652271    -------
439803    -------
           ...   
441129    -------
53863     -------
185612    -------
202773    -------
422081    -------
Name: FLAGS, Length: 3000, dtype: object

In [124]:
fdata.FLAGS.unique()

array(['-------', '---A---'], dtype=object)

In [125]:
fdata['FLAGS']= label_encoder.fit_transform(fdata['FLAGS'])
fdata['FLAGS'].unique()

array([0, 1])

In [126]:
fdata['FLAGS']=fdata['FLAGS'].astype(float)
fdata['FLAGS']

758701    0.0
5282      0.0
269110    0.0
652271    0.0
439803    0.0
         ... 
441129    0.0
53863     0.0
185612    0.0
202773    0.0
422081    0.0
Name: FLAGS, Length: 3000, dtype: float64

In [127]:
fdata['PKT_CLASS']

758701    UDP-Flood
5282         Normal
269110       Normal
652271       Normal
439803       Normal
            ...    
441129       Normal
53863        Normal
185612       Normal
202773       Normal
422081       Normal
Name: PKT_CLASS, Length: 3000, dtype: object

In [128]:
fdata.PKT_CLASS.unique()

array(['UDP-Flood', 'Normal', 'SIDDOS', 'Smurf', 'HTTP-FLOOD'],
      dtype=object)

In [129]:
fdata['PKT_CLASS']= label_encoder.fit_transform(fdata['PKT_CLASS'])
fdata['PKT_CLASS'].unique()

array([4, 1, 2, 3, 0])

In [130]:
fdata['PKT_CLASS']

758701    4
5282      1
269110    1
652271    1
439803    1
         ..
441129    1
53863     1
185612    1
202773    1
422081    1
Name: PKT_CLASS, Length: 3000, dtype: int32

In [131]:
fdata['PKT_CLASS']

758701    4
5282      1
269110    1
652271    1
439803    1
         ..
441129    1
53863     1
185612    1
202773    1
422081    1
Name: PKT_CLASS, Length: 3000, dtype: int32

In [132]:
fdata['PKT_CLASS']=fdata['PKT_CLASS'].astype(float)
fdata['PKT_CLASS']

758701    4.0
5282      1.0
269110    1.0
652271    1.0
439803    1.0
         ... 
441129    1.0
53863     1.0
185612    1.0
202773    1.0
422081    1.0
Name: PKT_CLASS, Length: 3000, dtype: float64

## Converting to Float

In [133]:
fdata['PKT_RATE']

758701    962.685
5282      124.943
269110    328.205
652271    124.941
439803    328.562
           ...   
441129    124.942
53863     328.193
185612    328.264
202773     328.46
422081    328.218
Name: PKT_RATE, Length: 3000, dtype: object

In [134]:
fdata.PKT_RATE.unique()

array([962.684973, 124.943426, 328.204637, 124.940628, 328.561918,
       1016.496869, 328.20604199999997, 328.217832, 124.942826,
       '328.561918', 328.491489, 328.205808, 328.16776699999997,
       124.943825, 328.19309, 328.460131, 328.431807, 328.52294700000004,
       124.942427, 124.943026, 124.94122800000001, 328.11323,
       328.26403999999997, 328.297902, 328.192835, 328.316229, 328.113525,
       328.06386200000003, 328.46027799999996, 328.24105099999997,
       328.218006, 1016.5491699999999, 328.20485099999996, 1016.424609,
       1016.418257, 124.944425, 124.943226, 1016.4372, 328.167486,
       94.7212, 328.43200099999996, 328.522879, 656.270166, 124.944225,
       '328.491489', 328.491596, 1118.27935, 328.064183, 124.944025,
       328.26412, 124.943625, 328.561898, 124.941427, 1016.449678,
       124.941827, 124.940828, '328.522947', 1016.5229619999999,
       1066.08599, 1016.443439, 124.941028, 328.29785499999997,
       124.941627, '124.941827', 95.145988, 124.94

In [135]:
fdata['PKT_RATE']=fdata['PKT_RATE'].astype(float)
fdata['PKT_RATE']

758701    962.684973
5282      124.943426
269110    328.204637
652271    124.940628
439803    328.561918
             ...    
441129    124.942027
53863     328.192835
185612    328.264040
202773    328.460278
422081    328.217832
Name: PKT_RATE, Length: 3000, dtype: float64

## Features

In [136]:
X=fdata.iloc[0:26]
X=fdata.drop(['PKT_CLASS'],axis=1)
X

SRC_ADD  DES_ADD  PKT_ID  FROM_NODE  TO_NODE  PKT_TYPE  PKT_SIZE  \
758701    12.20    24.54   21921         23       24       1.0      1500   
5282      12.10    24.32  592525         22       23       1.0      1000   
269110     5.00    24.50  156294          5       21       3.0      1540   
652271    19.10    24.39  585756         23       24       1.0      1000   
439803    24.10    10.00  364307         24       23       0.0        55   
...         ...      ...     ...        ...      ...       ...       ...   
441129     6.10    24.26  586343          6       21       1.0      1000   
53863      6.00    24.60  539099         21       23       3.0      1540   
185612     2.00    24.20  195349          2       21       3.0      1540   
202773    24.13    13.00   68748         24       23       0.0        55   
422081     4.00    24.40   72956          4       21       3.0      1540   

        FLAGS  FID    PKT_RATE  BYTE_RATE  PKT_AVG_SIZE  UTILIZATION  \
758701    0.0   33  962.684973  1444030.0        1500.0     0.123811   
5282      0.0   33  124.943426   124943.0        1000.0     0.059605   
269110    0.0    6  328.204637   505434.0        1540.0     0.236321   
652271    0.0   40  124.940628   124941.0        1000.0     0.059605   
439803    0.0   11  328.561918    18070.9          55.0     0.008446   
...       ...  ...         ...        ...           ...          ...   
441129    0.0   27  124.942027   124942.0        1000.0     0.059605   
53863     0.0    7  328.192835   505416.0        1540.0     0.236321   
185612    0.0    3  328.264040   505526.0        1540.0     0.236321   
202773    0.0   14  328.460278    18065.3          55.0     0.008446   
422081    0.0    5  328.217832   505455.0        1540.0     0.236321   

        PKT_DELAY  PKT_SEND_TIME  PKT_RESEVED_TIME  FIRST_PKT_SENT  \
758701   0.033071      21.420143         21.453214        1.000000   
5282     0.000400      55.512000         55.542640       25.000000   
269110   0.000000      15.929028         15.959397        1.000000   
652271   0.001520      52.816000         52.847760       25.000000   
439803   0.000000      33.572864         33.602874        1.030013   
...           ...            ...               ...             ...   
441129   0.000960      53.056000         53.087200       25.000000   
53863    0.000124      46.979472         47.009965        1.000000   
185612   0.000000      19.605427         19.635797        1.000000   
202773   0.000000       7.681331          7.711341        1.030032   
422081   0.000000       8.079406          8.109776        1.000000   

        LAST_PKT_RESEVED  
758701          9.990480  
5282           75.022640  
269110         50.027339  
652271         75.023760  
439803         50.040562  
...                  ...  
441129         75.023200  
53863          50.029102  
185612         50.018467  
202773         50.055747  
422081         50.025368  

[3000 rows x 18 columns]

## Setting Target

In [137]:
Y=fdata['PKT_CLASS']
Y

758701    4.0
5282      1.0
269110    1.0
652271    1.0
439803    1.0
         ... 
441129    1.0
53863     1.0
185612    1.0
202773    1.0
422081    1.0
Name: PKT_CLASS, Length: 3000, dtype: float64

pip install streamlit

## Training and Testing

In [138]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test =train_test_split(X,Y,stratify=Y,test_size=0.20,random_state=3)

## KNN Classifier

In [139]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 8).fit(X_train, Y_train)

## Confusion matrix and Accuracy

In [140]:
from sklearn.metrics import confusion_matrix, classification_report
knn_predictions = knn.predict(X_test)
cm = confusion_matrix(Y_test, knn_predictions)
print(cm)

[[  0   1   0   0   0]
 [  0 537   0   0   0]
 [  0   1   0   0   0]
 [  0   3   0   0   0]
 [  0   6   0   0  52]]


In [141]:
accuracy = knn.score(X_test, Y_test)
print (accuracy)

0.9816666666666667


from sklearn.metrics import accuracy_score
st.subheader('Model Test Accuracy Score: ')
st.write(str(accuracy_score(Y_test, knn_predictions)*100)+'%')
#print ('Accuracy Score :',accuracy_score(Y_test, knn_predictions))
#prediction = knn_predictions(user_input)

In [142]:
#streamlit run "C:\Users\sravani\OneDrive\Desktop\DDOS"

In [143]:
!pip list

Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
altair                             4.2.0
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
anyio                              3.5.0
argh                               0.26.2
argon2-cffi                        21.3.0
argon2-cffi-bindings               21.2.0
asn1crypto                         1.3.0
astor                              0.8.1
astroid                            2.4.2
astropy                            4.0.1.post1
atomicwrites                       1.4.0
attrs                              19.3.0
autopep8                           1.5.3
Babel                              2.8.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref              

# **FRONT-END**

In [144]:
import warnings
warnings.filterwarnings('ignore')

import ipywidgets as widgets
from IPython.display import display, clear_output

In [145]:
#!jupyter nbextension enable --py widgetsnbextension --sys-prefix
#!jupyter serverextension enable voila --sys-prefix

In [146]:
# Image Widget

file = open("ddos.jpg", "rb")
image = file.read()

image_headline = widgets.Image(
                    value=image,
                    format='jpg',
                    height='300',
                    width='300'
                )

label_headline = widgets.Label(
                    #value='Photo by CDC on Unsplash',
                    style={'description_width': 'initial'}
                )

vbox_headline = widgets.VBox([image_headline, label_headline])

In [147]:

grand = widgets.ToggleButtons(
            options=['Enter Website URL' ]
        )

In [148]:
name = widgets.Text(placeholder='Enter URL')

In [149]:


srcid = widgets.IntSlider(
            value=3, # default value
            min=0, 
            max=20,
            step=1.5,
            style={'description_width': 'initial', 'handle_color': '#16a085'} 
        )

desid = widgets.IntSlider(
            value=0, # default value
            min=0, 
            max=30,
            step=1.5,
            style={'description_width': 'initial', 'handle_color': '#16a085'} 
        )

In [150]:
# button send

button_send = widgets.Button(
                description='SUBMIT',
                tooltip='Send',
                style={'description_width': 'initial'}
            )

output = widgets.Output()

def on_button_clicked(event):
    with output:
        clear_output()
        print("Sent message: ")
        print(f"User {grand.value}, {name.value}.")
        
        print(f"SourceId is {srcid.value}")
        print(f"DestinationId is {desid.value}")
        print(f"DDOS Attack Detected")
        print(f"Would you like to continue or exit")

button_send.on_click(on_button_clicked)

vbox_result = widgets.VBox([button_send, output])

In [151]:
text_0 = widgets.HTML(value="<h1>DDOS ATTACK DETECTION!</h1>")
text_1 = widgets.HTML(value="<h2>Enter URL</h2>")
text_2 = widgets.HTML(value="<h3>Enter SourceID</h3>")
text_3 = widgets.HTML(value="<h3>Enter DestinationID</h3>")
vbox_text = widgets.VBox([text_0, text_1, grand, name, text_2,srcid,text_3,desid,vbox_result])

In [152]:
page = widgets.HBox([vbox_headline, vbox_text])
display(page)

In [153]:
### overfitting and underfitting

In [154]:
X1=fdata.iloc[0:26]
X1=fdata.drop(['PKT_CLASS'],axis=1)
X1

SRC_ADD  DES_ADD  PKT_ID  FROM_NODE  TO_NODE  PKT_TYPE  PKT_SIZE  \
758701    12.20    24.54   21921         23       24       1.0      1500   
5282      12.10    24.32  592525         22       23       1.0      1000   
269110     5.00    24.50  156294          5       21       3.0      1540   
652271    19.10    24.39  585756         23       24       1.0      1000   
439803    24.10    10.00  364307         24       23       0.0        55   
...         ...      ...     ...        ...      ...       ...       ...   
441129     6.10    24.26  586343          6       21       1.0      1000   
53863      6.00    24.60  539099         21       23       3.0      1540   
185612     2.00    24.20  195349          2       21       3.0      1540   
202773    24.13    13.00   68748         24       23       0.0        55   
422081     4.00    24.40   72956          4       21       3.0      1540   

        FLAGS  FID    PKT_RATE  BYTE_RATE  PKT_AVG_SIZE  UTILIZATION  \
758701    0.0   33  962.684973  1444030.0        1500.0     0.123811   
5282      0.0   33  124.943426   124943.0        1000.0     0.059605   
269110    0.0    6  328.204637   505434.0        1540.0     0.236321   
652271    0.0   40  124.940628   124941.0        1000.0     0.059605   
439803    0.0   11  328.561918    18070.9          55.0     0.008446   
...       ...  ...         ...        ...           ...          ...   
441129    0.0   27  124.942027   124942.0        1000.0     0.059605   
53863     0.0    7  328.192835   505416.0        1540.0     0.236321   
185612    0.0    3  328.264040   505526.0        1540.0     0.236321   
202773    0.0   14  328.460278    18065.3          55.0     0.008446   
422081    0.0    5  328.217832   505455.0        1540.0     0.236321   

        PKT_DELAY  PKT_SEND_TIME  PKT_RESEVED_TIME  FIRST_PKT_SENT  \
758701   0.033071      21.420143         21.453214        1.000000   
5282     0.000400      55.512000         55.542640       25.000000   
269110   0.000000      15.929028         15.959397        1.000000   
652271   0.001520      52.816000         52.847760       25.000000   
439803   0.000000      33.572864         33.602874        1.030013   
...           ...            ...               ...             ...   
441129   0.000960      53.056000         53.087200       25.000000   
53863    0.000124      46.979472         47.009965        1.000000   
185612   0.000000      19.605427         19.635797        1.000000   
202773   0.000000       7.681331          7.711341        1.030032   
422081   0.000000       8.079406          8.109776        1.000000   

        LAST_PKT_RESEVED  
758701          9.990480  
5282           75.022640  
269110         50.027339  
652271         75.023760  
439803         50.040562  
...                  ...  
441129         75.023200  
53863          50.029102  
185612         50.018467  
202773         50.055747  
422081         50.025368  

[3000 rows x 18 columns]

In [155]:
Y1=fdata['PKT_CLASS']
Y1

758701    4.0
5282      1.0
269110    1.0
652271    1.0
439803    1.0
         ... 
441129    1.0
53863     1.0
185612    1.0
202773    1.0
422081    1.0
Name: PKT_CLASS, Length: 3000, dtype: float64

In [156]:
from sklearn.model_selection import train_test_split
X1_train,X1_test,Y1_train,Y1_test =train_test_split(X1,Y1,stratify=Y,test_size=0.20,random_state=3)

In [157]:
print(X1_train.shape)
print(Y1_train.shape)
print(X1_test.shape)
print(Y1_test.shape)

(2400, 18)
(2400,)
(600, 18)
(600,)


In [158]:
from sklearn import tree
clf_2 = tree.DecisionTreeClassifier(min_samples_split=2)
clf_2.fit(X1_train,Y1_train)
pred_2 = clf_2.predict(X1_test)

In [159]:
print(pred_2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1.
 1. 1. 1. 1. 1. 4. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 4. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 1. 3. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 4. 1. 3.
 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 4. 1. 1. 1. 1. 4. 1. 1. 4. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 4. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1.

In [160]:
pred_train = clf_2.predict(X1_train)
pred_train

array([1., 1., 1., ..., 1., 1., 1.])

In [161]:
print("Test Data : ",accuracy_score(Y1_test,pred_2))
print("Train Data : ",accuracy_score(Y1_train,pred_train))

Test Data :  0.98
Train Data :  1.0


In [162]:
from sklearn.neighbors import KNeighborsClassifier
knn1 = KNeighborsClassifier(n_neighbors = 5).fit(X1_train, Y1_train)
knn_pred =knn1.predict(X1_test)

In [163]:
print(knn_pred)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1.
 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 4. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 4. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 4. 1. 1. 1. 1. 4. 1. 1. 4. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 4. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1. 4. 1. 1. 1. 1. 1.

In [164]:
predi_train = knn1.predict(X1_train)
predi_train

array([1., 1., 1., ..., 1., 1., 1.])

In [165]:
from sklearn.metrics import accuracy_score
print("Test Data : ",accuracy_score(Y1_test,knn_pred))
print("Train Data : ",accuracy_score(Y1_train,predi_train))

Test Data :  0.985
Train Data :  0.9908333333333333


In [167]:

# evaluate decision tree performance on train and test sets with different tree depths
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from matplotlib import pyplot
# create dataset
X1=data.drop(['PKT_CLASS'],axis=1)
y1=data['PKT_CLASS']
# split into train test sets
X1_train,X1_test,y1_train,y1_test = train_test_split(X1,y1,stratify=y1,test_size=0.20,random_state=0)
# define lists to collect scores
train_scores, test_scores = list(), list()
# define the tree depths to evaluate
values = [i for i in range(1, 21)]
# evaluate a decision tree for each depth
for i in values:
	# configure the model
	model = DecisionTreeClassifier(max_depth=i)
	# fit model on the training dataset
	model.fit(X1_train, y1_train)
	# evaluate on the train dataset
	train_yhat = model.predict(X1_train)
	train_acc = accuracy_score(y1_train, train_yhat)
	train_scores.append(train_acc)
	# evaluate on the test dataset
	test_yhat = model.predict(X1_test)
	test_acc = accuracy_score(y1_test, test_yhat)
	test_scores.append(test_acc)
	# summarize progress
	print('>%d, train: %.3f, test: %.3f' % (i, train_acc, test_acc))
# plot of train and test scores vs tree depth
pyplot.plot(values, train_scores, '-o', label='Train')
pyplot.plot(values, test_scores, '-o', label='Test')
pyplot.legend()
pyplot.show()

ValueError: Input contains NaN